version: '3.8'

services:

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data

  #app:
    #build:
     # context: .
     # dockerfile: Dockerfile
    #container_name: api-pets
    #environment:
      #NODE_ENV: development  # Configura el entorno como desarrollo
     # POSTGRES_HOST: ${POSTGRES_HOST}
    #  POSTGRES_PORT: ${POSTGRES_PORT}
     # POSTGRES_USER: ${POSTGRES_USER}
      #POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     # POSTGRES_DB: ${POSTGRES_DB}
    #ports:
   #   - '3000:3000'
  #  depends_on:
 #     - postgres
 #   volumes:
      #- ./src:/app/src

  #pgadmin:
  #  image: dpage/pgadmin4
  #  restart: always
  #  container_name: api-pets-pgadmin4
  #  environment:
  #    - PGADMIN_DEFAULT_EMAIL=admin@admin.com
  #    - PGADMIN_DEFAULT_PASSWORD=pgadmin4
  #  ports:
  #   - '5050:80'
  #  depends_on:
  #   - postgres